[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "tranfi"
version = "0.1.0"
description = "Streaming ETL language + runtime"
license = {text = "MIT"}
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["tranfi*"]
